base: tc_o320_o1280_local

default_host: atos_ac_pristine
allowed_hosts:
  prepare: [atos_ac_pristine]
  predict: [atos_ac_pristine]
  run: [atos_ac_pristine]
  evaluate: [atos_ac_pristine]
  scoreboard: [atos_ac_pristine]

evaluator_groups:
  default: [mlflow, tc, surface, probabilistic, region_plot, local_global]
  diagnostics: []

regions:
  interesting:
    franklin_outer: [15.0, 38.0, -78.0, -58.0]
    franklin_core: [20.0, 33.0, -72.0, -60.0]
    idalia_outer: [10.0, 40.0, -100.0, -80.0]
    idalia_core: [20.0, 33.0, -92.0, -80.0]
    gulf_transition: [18.0, 31.0, -96.0, -84.0]
    atlantic_transition: [18.0, 33.0, -82.0, -66.0]
  detail: {}

resource_profiles:
  predict:
    qos: ng
    gpus: 1
    ntasks_per_node: 1
    time: "12:00:00"
    mem: 160G
    cpus: 16
  evaluate:
    time: "04:00:00"
    mem: 64G
    cpus: 8
  evaluate_tc:
    time: "02:00:00"
    mem: 64G
    cpus: 8
  evaluate_surface:
    time: "02:00:00"
    mem: 64G
    cpus: 4
  evaluate_region_plot:
    time: "02:00:00"
    mem: 64G
    cpus: 8
  evaluate_probabilistic:
    time: "02:00:00"
    mem: 64G
    cpus: 8
  scoreboard:
    time: "00:30:00"
    mem: 16G
    cpus: 1
